### ISSUE TITLE
Please link to learning resources on the methods used

### ISSUE THREAD

**Issue by loksonarius** [selicia/splatistics#1]
Really interested to see where this project goes as it'd fit nicely with another project I've been considering taking on.

To be honest, I've not done ML/DM work in ages, but this so far seems pretty understandable. I'm kinda struggling to understand what the overall methodology being used in the `Optimizer.crossover` and `Loadout.get_fitness` functions though . 😅 

Could you link (either in comments or the README) a list of summaries on what the method being used is to determine optimal amounts of each ability per build? It'd really make going through the repo much easier. 😄

Might also be worth adding some disclaimer down the line specifying what "optimal" means in terms of what's being measured. 🙏

**Comment by selicia** [comment]
This project is still very much in its early phase of development. I was curious what would happen if a genetic algorithm tried to optimize loadouts purely based on the net gain to stats they provided.
 
That said, the logic behind the _fitness function_ (which determines the score of a loadout) is pretty crude right now. 

So, for example, let's say a build uses 1 Main and 2 Subs of Run Speed Up (which would be equal to 16AP). The fitness function uses Lean's `lerp` function along with the AP for the stat in the loadout to determine the stat's value would be. Let's assume the weapon being uses is the _.96 Gal_. The base Run Speed for it is `0.96`. However, with 16 AP (Ability Points, see _Section II.C_ of lean's [paper](http://leanny.github.io/paper/abilities.pdf)) of Run Speed Up we get to a Run Speed of `1.1802624`. So the _fitness function_ will, for the Run Speed stat, take the percentage increase of the stat and add it to the loadout's _fitness score_.

In _loadout.py_ you can see this in the following code snippet:
```
delta = abs((run_speed / run_speed_parameters[2] - 1) * 100)
self.fitness_score += delta
```

So for our values, we would get: `22.9 = ((1.1802624 / 0.96 - 1) * 100)` which means that the loadout's benefit from 16 AP is a `22.9%` increase from a stat. The fitness function then does this for *all* stats that I've coded it to consider. Some, like MPU, are not implemented yet.

You may notice that some stats, like Run Speed, actually have multiple stat effects. To account for this, I originally simply had the fitness function add relevant stat increases to the fitness function per weapon class. 
```
self.fitness_score += abs((run_speed / run_speed_parameters[2] - 1) * 100)
self.fitness_score += abs((run_speed_firing / run_speed_firing_parameters[2] - 1) * 100)
self.fitness_score += abs((run_speed_charging / run_speed_charging_parameters[2] - 1) * 100)
```

However, in a new update I plan on committing, I'm changing it to average all of the benefits provided by an individual stat, and then increasing that value by the number of benefits the stat provided. The goal is to reduce the impact (bias) the optimizer will have on stats with compounding benefits. To put this more clearly, it will look something like this:
```
run_speed_score = 0
run_speed_score += abs((run_speed / run_speed_parameters[2] - 1) * 100)
run_speed_score += abs((run_speed_firing / run_speed_firing_parameters[2] - 1) * 100)
run_speed_score += abs((run_speed_charging / run_speed_charging_parameters[2] - 1) * 100)
delta = (run_speed_score / 3) * 1.3
self.fitness_score += delta
```

As for the specific methodology I'm using for the genetic algorithm, take a look at these wikipedia pages for a great example of what is happening in `crossover` and `optimize.py`:
[1. Genetic Algorithms - Read all of it, but I'm using the "Elitism" implementation for generational evolution](https://en.wikipedia.org/wiki/Genetic_algorithm)
[2. Crossover - See Section on "Uniform Crossover"](https://en.wikipedia.org/wiki/Crossover_(genetic_algorithm))
[3. Mutation - See Section on "Uniform Mutation"](https://en.wikipedia.org/wiki/Mutation_(genetic_algorithm))

Feel free to ask more questions or suggest ideas for how to implement and improve this. It's very open ended and just something I wanted to try for fun and see what loadout's provided the most stat benefits.

**Comment by loksonarius** [comment]
Gorsh that's quite a write up!
Thank you for taking the time to explain and link everything -- I really appreciate it!
I can take what you wrote up and make a basic README.md in a PR if that helps 😄

**Comment by loksonarius** [comment]
Created a PR to help others that come across this repo.
Feel free to edit/add/remove whatever you please from that README 😄

**Comment by selicia** [comment]
Thank you for the README.MD file! I merged it in to the repo.
